[package]
name = "pis"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
bitpiece = "0.1.10"
delve = { version = "0.3.0", features = ["derive"], default-features = false }
enum_all_values_const = "0.1.1"
primwrap = "1.1.0"
thiserror-no-std = "2.0.2"

[features]
std = ["thiserror-no-std/std"]
